/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session */
        post: operations["session_api_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alert */
        Alert: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Event */
            event: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "unprotected" | "protected";
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /** Tool */
            tool?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "alert";
        };
        /**
         * Controls
         * @description Which Ledgerline controls are switched on for the protected run.
         */
        Controls: {
            /**
             * Pinning
             * @default true
             */
            pinning: boolean;
            /**
             * Strict Parsing
             * @default true
             */
            strict_parsing: boolean;
            /**
             * Verify Each Call
             * @default true
             */
            verify_each_call: boolean;
        };
        /** Coverage */
        Coverage: {
            /** Controls */
            controls: string[];
            /** Rows */
            rows: components["schemas"]["CoverageRow"][];
        };
        /** CoverageRow */
        CoverageRow: {
            /** Category */
            category: string;
            /** Cells */
            cells: {
                [key: string]: "required" | "not_needed" | "not_stopped";
            };
            /** Owasp Asi */
            owasp_asi: string[];
            /** Owasp Mcp */
            owasp_mcp: string[];
            /**
             * Protected
             * @enum {string}
             */
            protected: "harmed" | "safe";
            /** Scenario Id */
            scenario_id: string;
            /** Title */
            title: string;
            /**
             * Unprotected
             * @enum {string}
             */
            unprotected: "harmed" | "safe";
        };
        /** Decision */
        Decision: {
            /**
             * Action
             * @enum {string}
             */
            action: "blocked" | "replaced" | "rejected";
            /** Control */
            control: string;
            /** Method */
            method?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "unprotected" | "protected";
            /** Reason */
            reason: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "decision";
        };
        /** Exfiltration */
        Exfiltration: {
            /** Data */
            data: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "unprotected" | "protected";
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "exfiltration";
            /** Via */
            via: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * Menu
         * @description The tool list the agent can see after a listing (what the model reads).
         */
        Menu: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "unprotected" | "protected";
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /** Step */
            step: number;
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /** Tools */
            tools: components["schemas"]["ToolDef"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "menu";
        };
        /** MessageEvent */
        MessageEvent: {
            /** Body */
            body?: unknown;
            /**
             * Internal
             * @default false
             */
            internal: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "request" | "notification" | "response" | "invalid";
            /** Method */
            method?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "unprotected" | "protected";
            /** Msg Id */
            msg_id?: string | number | null;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Source
             * @enum {string}
             */
            source: "host" | "ledgerline" | "server";
            /** Summary */
            summary: string;
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /**
             * Target
             * @enum {string}
             */
            target: "host" | "ledgerline" | "server";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "message";
        };
        /** Outcome */
        Outcome: {
            /** Headline */
            headline: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "unprotected" | "protected";
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /** Stopped By */
            stopped_by?: string[];
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "outcome";
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "harmed" | "safe";
        };
        /**
         * Pinned
         * @description The tool definitions a person approved before the protected run (via `ledgerline pin`).
         */
        Pinned: {
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /** Tools */
            tools: components["schemas"]["ToolDef"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pinned";
        };
        /** RunFinished */
        RunFinished: {
            /** Error */
            error?: string | null;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Status
             * @enum {string}
             */
            status: "finished" | "failed";
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run_finished";
        };
        /** RunRecord */
        RunRecord: {
            controls: components["schemas"]["Controls"];
            /** Events */
            events: (components["schemas"]["RunStarted"] | components["schemas"]["Pinned"] | components["schemas"]["Step"] | components["schemas"]["MessageEvent"] | components["schemas"]["Decision"] | components["schemas"]["Alert"] | components["schemas"]["Menu"] | components["schemas"]["Exfiltration"] | components["schemas"]["Outcome"] | components["schemas"]["RunFinished"])[];
            /** Outcomes */
            outcomes: {
                [key: string]: components["schemas"]["Outcome"];
            };
            /** Run Id */
            run_id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Started At */
            started_at: number;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "finished" | "failed";
        };
        /** RunStarted */
        RunStarted: {
            controls: components["schemas"]["Controls"];
            /** Run Id */
            run_id: string;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run_started";
        };
        /** RunSummary */
        RunSummary: {
            controls: components["schemas"]["Controls"];
            /** Outcomes */
            outcomes: {
                [key: string]: components["schemas"]["Outcome"];
            };
            /** Run Id */
            run_id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Started At */
            started_at: number;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "finished" | "failed";
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            /** Category */
            category: string;
            /** Controls That Matter */
            controls_that_matter: string[];
            /** Difficulty */
            difficulty: string;
            /**
             * Expected Protected
             * @enum {string}
             */
            expected_protected: "harmed" | "safe";
            /**
             * Expected Unprotected
             * @enum {string}
             */
            expected_unprotected: "harmed" | "safe";
            /** Honest Note */
            honest_note: string;
            /** Id */
            id: string;
            /** Incident */
            incident: string;
            /** Owasp Asi */
            owasp_asi: string[];
            /** Owasp Mcp */
            owasp_mcp: string[];
            /** Steps */
            steps: string[];
            /** Story */
            story: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** SessionRequest */
        SessionRequest: {
            /** Token */
            token: string;
        };
        /** StartRun */
        StartRun: {
            controls?: components["schemas"]["Controls"];
            /** Scenario Id */
            scenario_id: string;
        };
        /** Step */
        Step: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Index */
            index: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "unprotected" | "protected";
            /**
             * Seq
             * @default 0
             */
            seq: number;
            /**
             * Status
             * @default done
             * @enum {string}
             */
            status: "done" | "skipped" | "error";
            /**
             * T Ms
             * @default 0
             */
            t_ms: number;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
        };
        /** ToolDef */
        ToolDef: {
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Sha256 */
            sha256: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    coverage_api_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coverage"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRun"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"][];
                };
            };
        };
    };
    session_api_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
